title: Rubrix
description: AI-powered test generator for AP Computer Science and Calculus
theme: jekyll-theme-cayman
show_downloads: true
github:
  repository_url: https://github.com/paderevski/rubrix
